import { Suspense } from "react";
import "../globals.css";
import Header from "@/components/header";
import Analytics from "@/components/analytics";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="min-h-screen ">
				<Suspense>
					<Analytics></Analytics>
				</Suspense>
				<Header></Header>
				<div className="px-20">{children}</div>
			</body>
		</html>
	);
}
